### ISSUE TITLE
Tutorial on how you did this?

### ISSUE THREAD

**Issue by phocodes** [glaukiol1/github-stats#1]
This looks awesome!
Are there any tutorials on how you did this?

**Comment by glaukiol1** [comment]
Its actually really simple! You can look at template.svg file, i have a simple javascript file that replaces the {{field}} in the svg file with the custom fields. You can look at how I get the data in the fetchers folder, then the calculate_stats.js file parses the responses. I use Vercel to deploy, I have the serverless function in the /api folder. Also to make the SVG i used https://boxy-svg.com

do you need any other info?

**Comment by phocodes** [comment]
thank you! and no I do not need any more information 
Tysm
